name = "DSPG_Manual"
uuid = "fc4e91ae-5e50-4eed-a323-80e0103cc5df"
authors = ["José Bayoán Santiago Calderón <jbs3hp@virginia.edu>"]
version = "0.1.0"

[compat]
Documenter = "0.24"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
